# https://github.com/orgs/community/discussions/25678
# https://github.com/orgs/community/discussions/25084
# https://github.com/jlumbroso/free-disk-space
# https://github.com/jlumbroso/free-disk-space
name: K230 CanMV Release

on:
  release:
    types: [released]
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

jobs:
  build_image:
    name: CanMV Build
    runs-on: [ubuntu-latest]
    timeout-minutes: 180
    strategy:
      matrix:
        cfg: ["canmv"]
    env:
        CONF: k230_${{ matrix.cfg }}_defconfig
    steps:
      - name: Check for dockerenv
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: show runner file and release runner disk space 
        run: |
          echo “show runner hostname”
          hostname
          echo “show runner user”
          whoami
          echo “show runner pwd”
          pwd
          echo “show runner kernel”
          uname -a
          echo "show runner disk usage BEFORE delete"
          df -h /
          echo "show current file"
          ls
          echo "${{ github.ref_name }} branch relese commit id ${{github.sha}}"  > release.txt
          # Copy compiled files to /github/workspace/artifacts
          sudo mkdir -p /github/workspace/artifacts
          sudo chown -R $(id -u):$(id -g) /github/workspace/artifacts
          sudo chmod -R 755 /github/workspace/artifacts
          cp release.txt /github/workspace/artifacts/
          ls -alht /github/workspace/artifacts/
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.cfg }}
          path: /github/workspace/artifacts/

  upload_release:
    needs: build_image
    name: CanMV Release
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifacts-*
          merge-multiple: true

      - name: Display Structure of Artifacts Files
        run: ls -R

      - name: Show Working Directory For Debug Purpose
        run: |
          echo “show runner hostname”
          hostname
          echo “show runner user”
          whoami
          echo “show runner pwd”
          pwd
          echo “show runner kernel”
          uname -a
          echo “show runner pwd file list”
          ls
          ls -alht
          echo “show runner artifacts”
          ls -alht artifacts || exit 0
          echo "github.ref: ${{github.ref}} "

      - name: Upload images to Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
  
  pre_release:
    needs: build_image
    name: CanMV Dev Branch PreRelease
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifacts-*
          merge-multiple: true

      - name: Display Structure of Artifacts Files
        run: ls -R

      - name: Show Working Directory For Debug Purpose
        run: |
          echo “show runner hostname”
          hostname
          echo “show runner user”
          whoami
          echo “show runner pwd”
          pwd
          echo “show runner kernel”
          uname -a
          echo “show runner pwd file list”
          ls
          ls -alht
          echo “show runner artifacts”
          ls -alht artifacts || exit 0
          
      - name: Delete current prerelease assets
        uses: andreaswilli/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.CR_PAT }}
          tagPrefix: 'PreRelease-'
          tag: ${{ github.ref_name }}
          deleteOnlyFromDrafts: true
      
      - name: Set Env
        run: |
          echo "BUILDTIME=$(TZ=Asia/Shanghai date)" >> $GITHUB_ENV
        
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: PreRelease-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - name: Set Relese Txt
        run: |
          cat > prerelease.txt << 'EOF'
          Pre Release基于开发分支dev branch自动编译，并自动删除旧的编译，只保留当前最新的编译镜像，仅供测试使用
          Pre Release build with ${{ github.ref_name }} branch latest code updates, it will automatic delete old image and only keeping the latest version.
          Current ${{ github.ref_name }} branch build at ${{ env.BUILDTIME }} , git commit id ${{ github.sha }}
          <br>
          [k230_canmv](https://github.com/kendryte/k230_canmv)
          [k230_canmv_docs](https://github.com/kendryte/k230_canmv_docs)
          [k230_sdk](https://github.com/kendryte/k230_sdk)
          [k230_sdk_docs](https://github.com/kendryte/k230_sdk_docs)
          EOF

      - name: Upload images to PreRelease Asset
        uses: softprops/action-gh-release@v1
        if: ${{  success() }}
        with:
          tag_name: Prerelease-${{ github.ref_name }}
          files: |
            artifacts/*
          prerelease: true
          generate_release_notes: true
          body_path: prerelease.txt
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}
  
